version: 2
jobs:
  release:
    docker:
      - image: cimg/node:12.18
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "f2:c2:4b:d3:72:1b:b7:b2:3f:6b:4b:41:78:e8:f4:ba"
      - run:
          name: Install dependencies and Build assets
          command: |
            git config user.email "dev@codetot.com"
            git config user.name "CODE TOT JSC"
            rm -rf .github/
            rm -rf .circleci/
            rm -rf .editorconfig
            git add .
            git commit -m "Release package"
            git push origin HEAD:production-temp --force
            git reset --hard origin/master
            git merge origin/production-temp --no-ff --no-edit
            git push origin HEAD:production
            git push origin :production-temp

workflows:
  version: 2
  build_and_test:
    jobs:
      - release:
          filters:
            branches:
              only: master
